# world-name:
#  Entity-name: https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/EntityType.html
#    - Banned Item https://papermc.io/javadocs/paper/1.17/org/bukkit/Material.html

world:
  SKELETON:
    - BOW

world_nether:
  PIGLIN:
    - GOLDEN_SWORD